/*
 * This file was auto-generated by speedy-antlr-tool v1.4.3
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "LuaParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_LuaTranslator : public LuaParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *Start_Context_cls = NULL;
    PyObject *ChunkContext_cls = NULL;
    PyObject *BlockContext_cls = NULL;
    PyObject *StatContext_cls = NULL;
    PyObject *AttnamelistContext_cls = NULL;
    PyObject *AttribContext_cls = NULL;
    PyObject *RetstatContext_cls = NULL;
    PyObject *LabelContext_cls = NULL;
    PyObject *FuncnameContext_cls = NULL;
    PyObject *VarlistContext_cls = NULL;
    PyObject *NamelistContext_cls = NULL;
    PyObject *ExplistContext_cls = NULL;
    PyObject *ExpContext_cls = NULL;
    PyObject *VarContext_cls = NULL;
    PyObject *PrefixexpContext_cls = NULL;
    PyObject *FunctioncallContext_cls = NULL;
    PyObject *ArgsContext_cls = NULL;
    PyObject *FunctiondefContext_cls = NULL;
    PyObject *FuncbodyContext_cls = NULL;
    PyObject *ParlistContext_cls = NULL;
    PyObject *TableconstructorContext_cls = NULL;
    PyObject *FieldlistContext_cls = NULL;
    PyObject *FieldContext_cls = NULL;
    PyObject *FieldsepContext_cls = NULL;
    PyObject *NumberContext_cls = NULL;
    PyObject *StringContext_cls = NULL;

    public:
    SA_LuaTranslator(speedy_antlr::Translator *translator);
    ~SA_LuaTranslator();
    antlrcpp::Any visitStart_(LuaParser::Start_Context *ctx);

    antlrcpp::Any visitChunk(LuaParser::ChunkContext *ctx);

    antlrcpp::Any visitBlock(LuaParser::BlockContext *ctx);

    antlrcpp::Any visitStat(LuaParser::StatContext *ctx);

    antlrcpp::Any visitAttnamelist(LuaParser::AttnamelistContext *ctx);

    antlrcpp::Any visitAttrib(LuaParser::AttribContext *ctx);

    antlrcpp::Any visitRetstat(LuaParser::RetstatContext *ctx);

    antlrcpp::Any visitLabel(LuaParser::LabelContext *ctx);

    antlrcpp::Any visitFuncname(LuaParser::FuncnameContext *ctx);

    antlrcpp::Any visitVarlist(LuaParser::VarlistContext *ctx);

    antlrcpp::Any visitNamelist(LuaParser::NamelistContext *ctx);

    antlrcpp::Any visitExplist(LuaParser::ExplistContext *ctx);

    antlrcpp::Any visitExp(LuaParser::ExpContext *ctx);

    antlrcpp::Any visitVar(LuaParser::VarContext *ctx);

    antlrcpp::Any visitPrefixexp(LuaParser::PrefixexpContext *ctx);

    antlrcpp::Any visitFunctioncall(LuaParser::FunctioncallContext *ctx);

    antlrcpp::Any visitArgs(LuaParser::ArgsContext *ctx);

    antlrcpp::Any visitFunctiondef(LuaParser::FunctiondefContext *ctx);

    antlrcpp::Any visitFuncbody(LuaParser::FuncbodyContext *ctx);

    antlrcpp::Any visitParlist(LuaParser::ParlistContext *ctx);

    antlrcpp::Any visitTableconstructor(LuaParser::TableconstructorContext *ctx);

    antlrcpp::Any visitFieldlist(LuaParser::FieldlistContext *ctx);

    antlrcpp::Any visitField(LuaParser::FieldContext *ctx);

    antlrcpp::Any visitFieldsep(LuaParser::FieldsepContext *ctx);

    antlrcpp::Any visitNumber(LuaParser::NumberContext *ctx);

    antlrcpp::Any visitString(LuaParser::StringContext *ctx);

};